version: "3.9"
services:
  app:
    build: .
    env_file: .env
    restart: unless-stopped
    networks: [web]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on: [app]
    restart: unless-stopped
    networks: [web]

networks:
  web:
    driver: bridge
